ItemEvents.tooltip(event => {
    event.add("kubejs:basic_control_circuit", "§aULV级电路")
    event.add("kubejs:advanced_control_circuit", "§cLV级电路")
    event.add("kubejs:elite_control_circuit", "§bMV级电路")
    event.add("kubejs:ultimate_control_circuit", "§5HV级电路")
    event.add("kubejs:ultima_control_circuit", "§4EV级电路")
    event.add("kubejs:warped_ender_pearl", "潜行右键可设置个人传送点，右键传送到传送点")
    event.add("kubejs:hyper_stable_self_healing_adhesive", "§7选择性完全粘合，即使在撕裂或损坏时也有效")
    event.add("kubejs:black_body_naquadria_supersolid", "§7如液体般流动，不反射任何电磁波，完美地将其吸收与传递")
    event.add("kubejs:command_wand", "需要副手拿着命令方块，且只能放在创造稳定核心上方")
    event.add("kubejs:uruium_coil_block", ["可为超维度等离子锻炉提供32000K炉温", "恒星锻炉模式仅可使用该线圈"])
    event.add("kubejs:essence_block", "可用骨块在方块转换室转换获得")
    event.add("kubejs:draconium_block_charged", "可用注入龙力的黑曜石在方块转换室转换获得")
    event.add("minecraft:crimson_stem", "可用橡木原木在方块转换室转换获得")
    event.add("minecraft:warped_stem", "可用白桦原木在方块转换室转换获得")
    event.add("minecraft:bone_block", "可用钙块在方块转换室转换获得")
    event.add("minecraft:moss_block", "可用草方块在方块转换室转换获得")
    event.add("minecraft:sculk", "可用苔藓块在方块转换室转换获得")
    event.add("gtceu:magmatter_block", "将一组磁物质锭丢入创造之门获得")
    event.add("minecraft:command_block", "将磁流体约束恒星物质块丢入创造之门获得")
    event.add("minecraft:chain_command_block", "将连锁命令方块核心与即将打破的命令方块聚合获得")
    event.add("minecraft:repeating_command_block", "将循环命令方块核心与即将打破的连锁命令方块聚合获得")
    event.add("ad_astra:oxygen_loader", "§c仅合成，无法产出氧气")
})